default_agent: bank_iq_agent
agents:
  bank_iq_agent:
    name: bank_iq_agent
    entrypoint: bank_iq_agent.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::164543933824:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-bankiq
      execution_role_auto_create: false
      account: '164543933824'
      region: us-east-1
      ecr_repository: 164543933824.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-bank_iq_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: bank_iq_agent-A5EGRh7iT7
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:164543933824:runtime/bank_iq_agent-A5EGRh7iT7
      agent_session_id: 8b6a28e5-c44a-47e2-9c5f-9a8c2780d5e1
    codebuild:
      project_name: bedrock-agentcore-bank_iq_agent-builder
      execution_role: arn:aws:iam::164543933824:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-ddce657011
      source_bucket: bedrock-agentcore-codebuild-sources-164543933824-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: bank_iq_agent_mem-I72r3PCvWO
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:164543933824:memory/bank_iq_agent_mem-I72r3PCvWO
      memory_name: bank_iq_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
