default_agent: bank_iq_agent_v1
agents:
  bank_iq_agent_v1:
    name: bank_iq_agent_v1
    entrypoint: bank_iq_agent_v1.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::164543933824:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-bankiq
      execution_role_auto_create: false
      account: '164543933824'
      region: us-east-1
      ecr_repository: 164543933824.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-bank_iq_agent_v1
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: bank_iq_agent_v1-z50VYm5O93
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:164543933824:runtime/bank_iq_agent_v1-z50VYm5O93
      agent_session_id: d953eec7-c242-4d01-b456-1bcb5cd7a6a9
    codebuild:
      project_name: bedrock-agentcore-bank_iq_agent_v1-builder
      execution_role: arn:aws:iam::164543933824:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-491c2288f3
      source_bucket: bedrock-agentcore-codebuild-sources-164543933824-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: bank_iq_agent_v1_mem-P0ylJMD5oE
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:164543933824:memory/bank_iq_agent_v1_mem-P0ylJMD5oE
      memory_name: bank_iq_agent_v1_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
